name: zendvn_online
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.4
  provider: ^6.0.5
  flutter_swipe: ^1.0.1
  cached_network_image: ^3.2.3
  badges: ^3.1.1
  carousel_slider: ^4.2.1
  url_launcher: ^6.1.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/.
    - assets/json/.
    - assets/fonts/Josefin Sans/.

  fonts:
    - family: Josefin Sans
      fonts:
        - asset: assets/fonts/Josefin Sans/static/JosefinSans-Thin.ttf
          weight: 100
        - asset: assets/fonts/Josefin Sans/static/JosefinSans-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/Josefin Sans/static/JosefinSans-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Josefin Sans/static/JosefinSans-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/Josefin Sans/static/JosefinSans-Light.ttf
          weight: 300
        - asset: assets/fonts/Josefin Sans/static/JosefinSans-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Josefin Sans/static/JosefinSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/Josefin Sans/static/JosefinSans-Italic.ttf
          style: italic
        - asset: assets/fonts/Josefin Sans/static/JosefinSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/Josefin Sans/static/JosefinSans-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Josefin Sans/static/JosefinSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Josefin Sans/static/JosefinSans-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Josefin Sans/static/JosefinSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/Josefin Sans/static/JosefinSans-BoldItalic.ttf
          weight: 700
          style: italic
